/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project.gui.lecturer;
import javax.swing.JFrame;
import project.roles.*;
import project.utils.*;

/**
 *
 * @author Khoo Guo Hao
 */
public class DesignAssessment extends FrameFormat {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DesignAssessment.class.getName());

    /**
     * Creates new form DesignAssessment
     */
    public DesignAssessment() {
        initComponents();
        super.formatWindow("Design Module Assessment");
        
        InteractTxt.initDatabase();
        for (IntakeModule x : InteractTxt.allIntakeModule) {
            x.getAllIMDetails();
            String y = x.getIMID();
            System.out.println("Intake id = "+y);
            
            for (Assessment i : x.IM_Assessments) {
                System.out.println("Ass = "+i);
                i.getAllAssDetails();
            }
            if (y.equals("gayyyyyyy")) {
                System.out.println("Hit! = "+ y);
                x.setIMID("IMID1");
            }
        }
        for (Assessment x : InteractTxt.allAssessment) {
            x.getAllAssDetails();
        }

//        for (Lecturer x : InteractTxt.allLecturer) {
//            System.out.println(x.getLeader().getName());
//        }
//        
//        for (Leader x : InteractTxt.allLeader) {
//            x.getFullUserData();
//            if (x.getName().equals("keewenyew")) {
//                x.setName("wenyew");
//            }
//        }
//        
//        for (Leader x : InteractTxt.allLeader) {
//            System.out.println(x.getFullUserData());
//        }
//        
//        for (Lecturer x : InteractTxt.allLecturer) {
//            System.out.println(x.getLeader().getName());
//        }

            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 604, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DesignAssessment().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
